version: '3.3'
services:
#===========MYSQL CONFIG================
  db:
    container_name: mysql
    networks:
      - demo-net
    hostname: 'demo-sql'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
#===========BUSYBOX CONFIG================
  busybox:
    networks:
      - demo-net
    image: busybox
    container_name: busybox
    command: sh -c "while true; do sleep 3600; done"

volumes:
  my-db:
networks:
  demo-net:
    driver: bridge
